# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty
gem: [jekyll-paginate, jekyll-gists]

# Setup
title:            Jorge FDZ
tagline:          'Ilustraci칩n y dise침o'
description:      Ilustraci칩n y dise침o
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jorge Fdz'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
